### DISCUSSION TITLE
How do I blacklist widgets like before?

### DISCUSSION THREAD

**Discussion by baduhai** [luisbocanegra/plasma-panel-colorizer#146] [General]
I recently upgraded from 0.5.2 to 1.2, and I can't figure out how to blacklist widgets like I could before. I just want to get rid of the background for some widgets, like the icon only task manager and the separator.

**Comment by luisbocanegra** [comment]
By creating an override for the widget(s) and unchecking widget customization.

![Screenshot_20250116_113244](https://github.com/user-attachments/assets/ba625ac5-2efe-4b60-811d-cfa67e167dcf)

**Reply by baduhai** [reply]
Thank you! I did try the override option, but I had widget customization enabled with a fully transparent background, but that just kept the same background colour as the other widgets.

**Reply by luisbocanegra** [reply]
You're welcome. The reason I moved to this approach was to be able to customize individual widgets in a more granular way. Should probably explain this in the README as it's a common question. Also, if you have any suggestions on how to make configuring easier let me know.

**Reply by AndydeCleyre** [reply]
Is this written up and explained in more detail anywhere? When I do this on top of Fusion 3, the spacers are just black, with a color border when hovered over.

**Reply by luisbocanegra** [reply]
@AndydeCleyre can you try unchecking the Fallback option too in the override, like this:

![image](https://github.com/user-attachments/assets/071b6123-b0c8-46d6-b72f-b048e0abeca3)

then apply the override to the target widget(s) making sure it is the only one:

![image](https://github.com/user-attachments/assets/f5e29cbe-a9a6-44ca-8969-d9c79549b5d1)

**Reply by AndydeCleyre** [reply]
Thanks. Now hovering does not add the color border. But the background is still black. Is there somewhere in particular I should specify transparency?

**Reply by luisbocanegra** [reply]
Hmm that could be a bug, can you share some screenshots of the panel and the override settings?

Also, what's your plasma version? please share the output of `kinfo` command in terminal

**Reply by AndydeCleyre** [reply]
```yml
Operating System: Arch Linux 
KDE Plasma Version: 6.4.1
KDE Frameworks Version: 6.15.0
Qt Version: 6.9.1
Kernel Version: 6.15.4-zen2-1-zen (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800H with Radeon Graphics
Memory: 16 GiB of RAM (13.5 GiB usable)
Graphics Processor: AMD Radeon Graphics
```

![image](https://github.com/user-attachments/assets/fc7cc967-b3a8-489f-9059-4c8a1e82c72b)

![image](https://github.com/user-attachments/assets/66a4ce72-a80e-4b90-90f6-3d4057661d26)
