### ISSUE TITLE
[Bug]: Temporary panel background flicker when icon is added or removed to system tray

### ISSUE THREAD

**Issue by sagar297** [luisbocanegra/plasma-panel-colorizer#160]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [ ] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Nix package
- [x] Manually from the latest source code

**Describe the bug**
Panel background gets black for a split second when a new icon appears or disappears from system tray.
This bug first appeared on version v2.0.0 (commit: 342fa50 fix: update windows geometry on config changes).
Flickering stops if I remove the line 1473 `dbusKWinReconfigure.call()` from main.qml

**Steps to reproduce**

1. Launch an application that shows icon in system tray.
2. Observe the taskbar background

**Observed Result**
Panel background gets black for a second.

**Expected Result**
Panel background should not gets black for a second.

**Screenshots**

https://github.com/user-attachments/assets/d91d1df0-4339-418d-bab7-b330ecf6398c

**System information (please complete the following):**

```yaml
Operating System: EndeavourOS 
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.10.0
Qt Version: 6.8.1
Kernel Version: 6.12.10-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-4710HQ CPU @ 2.50GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4600
```
