### ISSUE TITLE
[Bug]: Panel bottom edge gets cut off when all spacers are transparent

### ISSUE THREAD

**Issue by AnicJov** [luisbocanegra/plasma-panel-colorizer#186]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Nix package
- [ ] Manually from the latest source code

**Bug Description**
When setting all spacers to transparent or disabled background & foreground in either the Preset Overrides or Global Overrides the panel's bottom edge gets cut off. As shown in the attached video and image.

**Steps to reproduce**

1. Add a floating panel on the top of the screen.
2. In Appearance, disable the panel background and configure widgets to have a background.
3. In Global Overrides, create a new override which disables the background.
4. Set all spacer widgets to use the new override.

**Observed Result**
The bottom edge of the panel gets cut off.

**Expected Result**
The bottom edge of the panel doesn't get cut off and stays the same as when the spacers have a background.

**Screenshots**

![Image](https://github.com/user-attachments/assets/addaaec3-2387-4ef0-9964-f0f940950301)

![Image](https://github.com/user-attachments/assets/ed9b8827-8cc4-436c-8c9e-c52b59617735)

https://github.com/user-attachments/assets/b0cd2ac5-bc60-4398-be5b-799e1b299c63

**System information (please complete the following):**

```yaml
Operating System: Manjaro Linux 
KDE Plasma Version: 6.3.1
KDE Frameworks Version: 6.11.0
Qt Version: 6.8.2
Kernel Version: 6.13.4-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 5900X 12-Core Processor
Memory: 62.7 GB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080
```

- Preset config file: [settings.json](https://gist.github.com/AnicJov/5a2ed9552c0e75a8a7220fac8ff5d199)

**Additional context**
I can confirm that this issue was not present in version 0.5.2 as I have that one running on another machine. This only started happening in versions >= 2.0

If you know if there is a way to fix this in my config please let me know, or if you need any additional info or assistance.
Thanks.
