### ISSUE TITLE
[Bug]: Applet causes memory leak in plasmashell (confirmed by kde dev)

### ISSUE THREAD

**Issue by hugalafutro** [luisbocanegra/plasma-panel-colorizer#187]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version

Install method used:

no idea it came with distro (garuda linux) its arch so updates are rolling

**Describe the bug**

https://discuss.kde.org/t/high-memory-usage-from-plasmashell-is-it-a-memory-leak/29105/27

**Steps to reproduce**
use the applet

**Observed Result**
memory usage of plasmashell grows infinitely (largest I seen was 9GB)

**Expected Result**
no memory leak

**Screenshots**
screenshots in the KDE thread above

**System information (please complete the following):**

```yaml
Operating System: Garuda Linux
KDE Plasma Version: 6.3.2
KDE Frameworks Version: 6.11.0
Qt Version: 6.8.2
Kernel Version: 6.13.5-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 12 × Intel® Xeon® E-2176M  CPU @ 2.70GHz
Memory: 23.4 GiB of RAM
Graphics Processor: Intel® UHD Graphics P630
```
