### ISSUE TITLE
[Bug]: Unable to force the icon color of Application Launcher

### ISSUE THREAD

**Issue by GrassBlock1** [luisbocanegra/plasma-panel-colorizer#201]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [ ] Using Plasma's "Add new widget" (KDE Store)
- [x] AUR
- [ ] Nix package
- [ ] Manually from the latest source code

**Describe the bug**
I use a svg file for the icon of application launcher, which is black:
![Image](https://github.com/user-attachments/assets/6898d974-58d9-408b-b853-15364dcda67b)

I can't force the color effect of it.

**Steps to reproduce**

1. Go to 'Configure Panel Colorizer'
2. Click on 'Text and Icons'
3. Click on the any of 'mask' 'effect' 'refresh' beside the 'Application Launcher'
4. Click on 'Apply'

**Observed Result**
Unable to click 'Apply', if I also changed other settings and click 'Apply', the color of icon doesn't change

**Expected Result**
The icon get recolored

**Screenshots**
<video src='https://github.com/user-attachments/assets/ff80d769-691b-478a-be64-59ab508cd279'></video>

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
# paste output of kinfo here
Operating System: Arch Linux 
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.11.0
Qt Version: 6.8.2
Kernel Version: 6.13.6-arch1-1-lily (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600U with Radeon Graphics
Memory: 13.5 GiB of RAM
Graphics Processor 1: AMD Radeon Graphics
Graphics Processor 2: NVIDIA GeForce MX450
```
