### ISSUE TITLE
[Bug]: Horizontal margin override now stretches plasmoids

### ISSUE THREAD

**Issue by angelbruni** [luisbocanegra/plasma-panel-colorizer#204]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [ ] Using Plasma's "Add new widget" (KDE Store)
- [x] AUR
- [ ] Nix package
- [ ] Manually from the latest source code

**Describe the bug**

**Steps to reproduce**

1. Go to 'Preset Overrides'
2. Create a new override
3. Modify its horizontal margin values
4. Apply override to a plasmoid

**Observed Result**
The plasmoids which have their horizontal margins overriden now look stretched and blurry (due to being stretched)

**Expected Result**
For it to work how it did before `v2.4.0` when it would modify the margins (or something more akin to padding if you have a background override)

**Screenshots**
![Image](https://github.com/user-attachments/assets/e4ad85cd-f4b0-4d22-a3a4-f436b2bb410d)

**System information:**

```yaml
Operating System: CachyOS Linux
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.2
Kernel Version: 6.13.7-2-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080
```

**Additional context**
I make heavy use of the margins override in multiple plasmoids and both my panels, so this is very noticeable to an user like me and makes the setup look really ugly.
