### ISSUE TITLE
[Bug]: Unified widget background for Panel Colorizer doesn't save some widgets

### ISSUE THREAD

**Issue by RedSnt** [luisbocanegra/plasma-panel-colorizer#208]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Nix package
- [ ] Manually from the latest source code

**Describe the bug**
When trying to use the unified widget backgrounds feature, one cannot set the Panel Colorizer widget as either a "start" or "end" piece, and even as the middle inbetween other widgets it doesn't look correct.

**Steps to reproduce**

1. Go to Panel colorizer settings -> Unified widget backgrounds on a non primary monitor.
2. Click on Panel colorizer, ***start or end***
3. ...
4. ...
5. Can't apply settings, almost like "no settings changes detected, therefore no need to apply" event happened.

**Observed Result**
Nothing showed in terminal output while pressing the buttons in Unified widget backgrounds and no errors reported when applying settings.

**Expected Result**
Expected to be able to integrate/unify panel colorizer button with other widgets on the panel.

**Screenshots**

<details><summary>Uploaded screenshot.</summary>

![Image](https://github.com/user-attachments/assets/1d63c4de-2930-4d8c-8f4d-856e6fcfe9b1)
</details>

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

<details><summary>kinfo output.</summary>

```yaml
Operating System: Nobara Linux 41
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.2
Kernel Version: 6.13.7-200.nobara.fc41.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × 11th Gen Intel® Core™ i9-11900K @ 3.50GHz
Memory: 62.6 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070 Ti
```
</details>

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]
Also using Smart Video Wallpaper Reborn of course.

**Additional context**
Not system breaking, in fact pretty benign, but it just means that panel colorizer gets hidden (as a preference) as it doesn't properly integrate when visible.  
PS: I just updated to version 2.4.1, which should be the current version.
