### ISSUE TITLE
[Bug]: Plasma crash when adding widgets

### ISSUE THREAD

**Issue by Vistaus** [luisbocanegra/plasma-panel-colorizer#209]
I have:

- [ x ] Searched if this issue hasn't been reported yet.
- [ x ] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [ x ] Using Plasma's "Add new widget" (KDE Store)
- [ x ] AUR
- [ ] Nix package
- [ ] Manually from the latest source code

**Describe the bug**

**Steps to reproduce**

1. Install the widget;
2. Try to add it to the panel.

**Observed Result**
Plasma crashes and restarts itself, withoud adding the widget.

**Expected Result**
I expected Plasma not to crash and for the widget to be added.

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
Operating System: CachyOS Linux 
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.2
Kernel Version: 6.13.7-1-cachyos-bmq-lto (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 9 5900HX with Radeon Graphics
Memory: 30.8 GiB of RAM
Graphics Processor: AMD Radeon Graphics
```
