### ISSUE TITLE
[Bug]: Stuck custom blur region after removing widget

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/plasma-panel-colorizer#210]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [ ] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Nix package
- [x] Manually from the latest source code

**Describe the bug**

Removing a widget from the panel when custom blur per widget is enabled leaves a stuck blur area

**Steps to reproduce**

1. Enable 'Blur Widgets' preset
2. Enter edit mode and remove any widget that is not 'Panel Colorizer' from the panel

**Observed Result**

A blur will appear to the right side of the panel and doesn't go away until restarting plasmashell

**Expected Result**

Blur region should be properly removed

**Screenshots**

![Image](https://github.com/user-attachments/assets/4f9034a3-bf51-412a-9771-8a1c41ebe7a5)

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
Operating System: Arch Linux 
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.2
Kernel Version: 6.13.8-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × Intel® Core™ i7-9750H CPU @ 2.60GHz
Memory: 31.1 GiB of RAM
Graphics Processor: Intel® UHD Graphics 630
```
