### ISSUE TITLE
[Bug]: Colorization using system colors Broken after Plasma 6.3.4 update

### ISSUE THREAD

**Issue by neo-nayan** [luisbocanegra/plasma-panel-colorizer#212]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Nix package
- [ ] Manually from the latest source code

**Describe the bug**
When you switch plasma theme to light mode, the widget background stays black

**Steps to reproduce**

1. Go to 'Appearance' in panel colorizer settings
2. Select on 'Widgets' under the element section.
3. Click the checkbox of 'Enable Widgets Customization'
4. Under 'Background Color' Section, click on Check the " Enable" Checkbox
5. For the "Source" of the background color, choose "Follow" 
6. "Element" under the Source is automatically on "Panel Background"
7. Click on "Apply" and "Okay"
8. Now try changing the system-wide color theme from dark theme to light theme using system settings..

**Observed Result**
The widget background stays black even after switching to a light theme.

**Expected Result**
If the widget background is set to "System" or "Follow" in Panel Colorizer settings, it should dynamically update between light and dark modes based on the system-wide colour theme.

**Screenshots**

- Check the panel of the top bar for both images after the Plasma 6.3.4 update. 
- The bottom panel or dock does not use panel colorizer as a control

![Image](https://github.com/user-attachments/assets/46188038-eb45-4587-9113-d7292772cca7)

![Image](https://github.com/user-attachments/assets/bc7fcb9e-33b4-44a1-9e86-f434eab37b2e)

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
Operating System: EndeavourOS 
KDE Plasma Version: 6.3.4
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.3
Kernel Version: 6.13.8-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i7-7600U CPU @ 2.80GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

```

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]
Colloid plasma theme
Force blur
Compact pager

**Additional context**
The panel background does not dynamically update to match the system’s theme when set to System or Follow.
This behaviour makes it seem like the dark mode works, but in reality, it does not dynamically adapt either.
