### ISSUE TITLE
[Bug]: Panel colorizer crash caused by ImageRoundedRectangle.qml

### ISSUE THREAD

**Issue by sahitono** [luisbocanegra/plasma-panel-colorizer#232]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Nix package
- [x] Manually from the latest source code

**Describe the bug**
Panel colorizer crash with this message
```
file:///home/sahit/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/main.qml:527:9: Type ImageRoundedRectangle unavailable

file:///home/sahit/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/ImageRoundedRectangle.qml:19:11: ".live" is not available due to component versioning.
```

**Steps to reproduce**

1. Add panel colorizer to the panel
2. Style not working showing the message above

**Observed Result**
journalctl show the message like above

**Expected Result**
Please describe

**Screenshots**

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
Operating System: Fedora Linux 42
KDE Plasma Version: 6.3.4
KDE Frameworks Version: 6.13.0
Qt Version: 6.8.2
Kernel Version: 6.14.2-300.fc42.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 22 × Intel® Core™ Ultra 7 155H
Memory: 30.9 GiB of RAM
Graphics Processor 1: Intel® Arc
Graphics Processor 2: NVIDIA GeForce RTX 4050 Laptop GPU

```

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]

**Additional context**
