### ISSUE TITLE
[Bug]: Unable to Install Dependencies on Fedora 42

### ISSUE THREAD

**Issue by YouCanTouCan** [luisbocanegra/plasma-panel-colorizer#233]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Nix package
- [ ] Manually from the latest source code

**Describe the bug**
When I go into the "Appearence" section of the settings, the following error appears:

![Image](https://github.com/user-attachments/assets/871ccde1-316d-4812-acb2-a3be6a5e458c)

Following the directions and link, I've gone to the ReadMe and ran the command `git gcc-c++ cmake extra-cmake-modules libplasma-devel spectacle python3 python3-dbus python3-gobject` in the terminal. However, I simply get the response git: `gcc-c++' is not a git command. See 'git --help'.` Sure enough, running `git --help` shows that it is not a command. I did some research and tried running `sudo dnf install @development-tools
`, but even after installing this, the command gave the same error. Should this be useful info, running `gcc --version` yields the response `gcc (GCC) 15.0.1 20250329 (Red Hat 15.0.1-0)`

I'm admittedly not super super technical (enough to run Linux, but not enough to use the commandline with confidence), so it is very likely this is something that should be obvious (hence seemingly no one else having any trouble with it). Many thanks for making this widget - I've been using it since it was just about new.

**Steps to reproduce**

1. Go to Panel Colorizer Settings
2. Click on the Appearence Tab
3. See the error message
4. Run the command in the terminal to install the dependencies
5. See yet another error message

**Observed Result**
Terminal error when attempting to install dependencies:
`git: 'gcc-c++' is not a git command. See 'git --help'.`

**Expected Result**
Dependencies should simply be installed, after which the error in the settings menu should disappear.

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
# Operating System: Fedora Linux 42
KDE Plasma Version: 6.3.4
KDE Frameworks Version: 6.13.0
Qt Version: 6.9.0
Kernel Version: 6.14.2-300.fc42.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13900HX
Memory: 31.0 GiB of RAM
Graphics Processor 1: Intel® Graphics
Graphics Processor 2: NVIDIA GeForce RTX 4080 Laptop GPU

```

- This is a fairly default setup - no strange add-ons or buggy things like Kvantum.

**Additional context**
I had this problem on Fedora 41 as well, but never bothered to do anything about it until now.
