### ISSUE TITLE
[Bug]: Cannot use global overrides to create island illusion

### ISSUE THREAD

**Issue by WunschK** [luisbocanegra/plasma-panel-colorizer#236]
Hi there, 
We have had a short stint on the thread in discuss.kde.org, and you asked me to create a bug report - Thus, here I am :-) 

I am using the latest version: Panel Colorizer 2.6

Install method used:
I added Panel Colorizer, using Plasma's "Add new widget".

**Describe the bug**
I wanted to override the panel spacer with a global override, to create the illusion of "islands"
However, if I disable the customisation the panel still seems like one big panel - when I activate and set a regular color, the spacer is colored.

**Steps to reproduce**

Unfortunately, I am not sure: 
I set up a global override as shown in the thread: 
https://discuss.kde.org/t/panel-colorizer-for-plasma-6/10675/26?u=wunschk

**Observed Result**
I couldn't find any logs 

**Expected Result**
Please describe

**Screenshots**

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
Operating System: openSUSE Tumbleweed 20250423
KDE Plasma Version: 6.3.4
KDE Frameworks Version: 6.13.0
Qt Version: 6.9.0
Kernel Version: 6.14.3-1-default (64-bit)
Graphics Platform: Wayland
Processors: 12 × 12th Gen Intel® Core™ i7-1255U
Memory: 31.0 GiB of RAM
Graphics Processor: Intel® Iris® Xe Graphics
```

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]
- Theme: Breeze Dark, with kvantum 
- no kwin-scripts that I can think of - with regards to relevance; maybe Application Title Bar? 
- not a lot of addons 

aditional info
the changes that I mde for the panel:

![Image](https://github.com/user-attachments/assets/59063322-ae4b-427b-940d-6e843cb335c8)

I am using get highlight color from wallpaper - maybe that is relevant

edit: 
added a journal.txt when trying to create it.
[journal.txt](https://github.com/user-attachments/files/19927605/journal.txt)

edit2: forgot to actually add the file :-D

edit 3: I tried to install the plguin manually, I couldN'T get it running, though
