### ISSUE TITLE
[Bug]: Maximised and Active is Per Screen

### ISSUE THREAD

**Issue by Cal-Nine** [luisbocanegra/plasma-panel-colorizer#238]
I have:

- [ x] Searched if this issue hasn't been reported yet.
- [x ] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [ ] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ x] Nix package
- [ ] Manually from the latest source code

**Describe the bug**
"Maximised window" with "Active window only" activates even when window is not active, when the active window is on another screen. This happens both when Window Behaviour > Multiscreen behaviour > Separate screen focus is selected or deselected in System Settings.

**Steps to reproduce**

1. Set Presets auto-loading to load one preset when Maximised window and Active window only are selected, and another preset for Normal.
2. Maximise a window
3. Move focus to a window on a different screen

**Observed Result**
Maximised window preset remains loaded

**Expected Result**
Normal preset is loaded.

**System information (please complete the following):**

```yaml
Operating System: NixOS 25.05
KDE Plasma Version: 6.3.4
KDE Frameworks Version: 6.13.0
Qt Version: 6.9.0
Kernel Version: 6.12.19 (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-1065G7 CPU @ 1.30GHz
Memory: 15.2 GiB of RAM
Graphics Processor: Intel® Iris® Plus Graphics
```
