### ISSUE TITLE
[Bug]: A widgets' shape radius and borders should still display when the widget is temporarily empty

### ISSUE THREAD

**Issue by AndydeCleyre** [luisbocanegra/plasma-panel-colorizer#245]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [ ] Using Plasma's "Add new widget" (KDE Store)
- [x] AUR (updated to 2.6.1 in a local checkout, ahead of AUR's 2.6.0)
- [ ] Nix package
- [ ] Manually from the latest source code

**Describe the bug**

I'm using a preset that "bubbles" widgets independently in groups, with a modified widget radius, border, and widget groupings. When a widget is temporarily empty -- like the icons only task manager with no windows open, or the global menu when the current app exports no menu -- and at the edge of a widget group, neither the radius nor the border are displayed there.

**Steps to reproduce**

1. Create a horizontal panel with a global menu at one end, an icons-only task manager at the other, and something else in the middle.
2. Activate the preset: Blur Widgets 2
3. Maybe unnecessary, but: Appearance>Widgets>Shape>Radius: 16,16,16,16
4. Maybe unnecessary, but: Appearance>Widgets>Border>Primary: 3.00
5. Close all windows, or focus a window with no global menu support.

**Observed Result**

The edges of the panel where the empty widgets are have no border or radius.

**Expected Result**

Those edges would have border and radius.

**Screenshots**

![Image](https://github.com/user-attachments/assets/dd842f64-27d8-4a64-8f63-101a18e051ce)

![Image](https://github.com/user-attachments/assets/06dba7bb-9008-44a4-ac62-009e9a1aa71a)

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output below

```yaml
Operating System: Arch Linux 
KDE Plasma Version: 6.3.4
KDE Frameworks Version: 6.13.0
Qt Version: 6.9.0
Kernel Version: 6.14.4-zen1-2-zen (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800H with Radeon Graphics
Memory: 13.5 GiB of RAM
Graphics Processor: AMD Radeon Graphics
```

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]

Karousel kwin script, Fluent plasma theme.

**Additional context**

🤷🏼
