### ISSUE TITLE
[Bug]: Icons get randomly blue

### ISSUE THREAD

**Issue by hrqmonteiro** [luisbocanegra/plasma-panel-colorizer#257]
I have:

- [X] Searched if this issue hasn't been reported yet.
- [X] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [X] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Nix package
- [ ] Manually from the latest source code

**Describe the bug**
Icons randomly get blue in the tray

**Steps to reproduce**

They just do. I just applied a margin override to Tray and Clock, no coloring whatsoever on anywhere else, but they randomly get blue

https://github.com/user-attachments/assets/58099650-f713-4263-86bf-43b40b724b62

**Observed Result**
Nothing, just the coloring

**Expected Result**
To not be like that

**Screenshots**

![Image](https://github.com/user-attachments/assets/5fe4ee1c-f35e-465f-abe1-a9a03ec9bedb)

**System information (please complete the following):**

```yaml
Operating System: Fedora Linux Asahi Remix 42
KDE Plasma Version: 6.3.5
KDE Frameworks Version: 6.14.0
Qt Version: 6.9.0
Kernel Version: 6.14.2-401.asahi.fc42.aarch64+16k (64-bit)
Graphics Platform: Wayland
Processors: 4 × Apple Avalanche (M2), 4 × Apple Blizzard (M2)
Memory: 7.3 GiB of RAM
Graphics Processor 1: Apple M2
Graphics Processor 2: llvmpipe
Product Name: Apple MacBook Air (13-inch, M2, 2022)
U-Boot Version: 2024.10
```

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]

N/A
