### ISSUE TITLE
[Bug]: Noisy journal from 4.3.0

### ISSUE THREAD

**Issue by pallaswept** [luisbocanegra/plasma-panel-colorizer#286]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Nix package
- [ ] Manually from the latest source code
- [x] Manually from github release

**Describe the bug**

Lots of messages in the journal since Colorizer 4.3.0

**Steps to reproduce**

These are the only settings I change:

![Image](https://github.com/user-attachments/assets/746f8c80-5002-44c7-97b2-bac5239efd50)

**Observed Result**

On plasma start, I see this in the journal:
```
Jun 08 18:18:35 Pallas plasmashell[49900]: qml: 999.999.999 4.3.0 true
Jun 08 18:18:35 Pallas plasmashell[49900]: qml: 999.999.999 4.3.0 true
```
and then every 5 seconds
```
Jun 08 18:18:40 Pallas plasmashell[49900]: qml: 4.3.0 4.3.0 true
Jun 08 18:18:40 Pallas plasmashell[49900]: qml: 4.3.0 4.3.0 true
Jun 08 18:18:45 Pallas plasmashell[49900]: qml: 4.3.0 4.3.0 true
Jun 08 18:18:45 Pallas plasmashell[49900]: qml: 4.3.0 4.3.0 true
```

**Expected Result**
Still pretty but less noisy 😆 

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
Operating System: openSUSE Tumbleweed 20250606
KDE Plasma Version: 6.3.5
KDE Frameworks Version: 6.14.0
Qt Version: 6.9.1
Kernel Version: 6.15.0-1-default (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 5900X 12-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3090
```

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]

I have colorizer on two panels (probably why the errors come in pairs?)
Also use panel spacer extended

Thanks Luis!
