### ISSUE TITLE
[Bug]: Can't load new preset or modified presets.

### ISSUE THREAD

**Issue by CcMenta** [luisbocanegra/plasma-panel-colorizer#289]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [ ] Using Plasma's "Add new widget" (KDE Store)
- [x] AUR
- [ ] Nix package
- [ ] Manually from the latest source code

**Describe the bug**
Can't load in newly created/modified presets.

**Steps to reproduce**

1. Create a new preset or modify an old preset.
2. load in the new/modified preset.

**Observed Result**
New presets simply doesn't load at all, and old preset

**Expected Result**
Load in the preset

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
Operating System: CachyOS Linux 
KDE Plasma Version: 6.3.5
KDE Frameworks Version: 6.15.0
Qt Version: 6.9.1
Kernel Version: 6.15.2-2-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6600

```

- Things in your system that might be relevant: Klassy theme.
