### ISSUE TITLE
[Bug]: Widget breaks floating applets

### ISSUE THREAD

**Issue by CeruleanDerpo** [luisbocanegra/plasma-panel-colorizer#293]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (see *Widget settings* > *About page* or *top right corner for version 1.1.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Nix package
- [ ] Manually from the latest source code

**Describe the bug**
This widget breaks the floating look of plasma's applets, this is especially noticeable because the applets' bottom will be cut off, especially when using plasma themes that add a big padding to the applet (such as utterly round)

**Steps to reproduce**
1. Add a panel
2. Set it to be floating (either Panel and Applets or Applets Only (Plasma 6.4+, otherwise it's just a toggle))
3. Open an applet in the panel (such as the application launcher) (they will float and be detached from the panel)
4. Add the panel colorizer widget to the panel (it doesn't need to be customized, the fact the widget is present on the panel is enough to trigger the bug for that panel)
5. Open the applet again

**Observed Result**
The applets won't float anymore, breaking a plasma feature

**Expected Result**
The applets are unaffected

**Screenshots**
Before adding the widget:
![Image](https://github.com/user-attachments/assets/093d7a17-fb4a-41d8-8840-ac5cd5ea1575)

After adding the widget:
![Image](https://github.com/user-attachments/assets/b43241e7-9be3-49dd-a3d6-cd7a89ad2e1a)

**System information (please complete the following):**
Run `kinfo` on a terminal and paste the output bellow

```yaml
Operating System: Fedora Linux 42
KDE Plasma Version: 6.4.0
KDE Frameworks Version: 6.15.0
Qt Version: 6.9.1
Kernel Version: 6.14.11-300.fc42.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8300H CPU @ 2.30GHz
Memory: 16 GiB of RAM (15.5 GiB usable)
Graphics Processor 1: NVIDIA GeForce GTX 1650
Graphics Processor 2: Intel® UHD Graphics 630
```

- Things in your system that might be relevant: N/A

**Additional context**
I tried on a separate user with no modifications apart from panel colorizer
